use_frameworks!

target 'ImageRecognitionDemo_Example' do
#  pod 'ImageRecognitionDemo', :path => '../'
  pod 'ImageRecognitionDemo', :git => 'https://github.com/liboloveguo/ImageRecognitionDemo.git'
  
  target 'ImageRecognitionDemo_Tests' do
    inherit! :search_paths

    
  end
end
